#[Info]
site_name: CXYHUKY
site_url: https://cxyhuky.github.io/
site_author: Kangying Hu

copyright: Copyright &copy; 2024 Kangying Hu
#[Config]
#[Repo Config]
repo_url: https://github.com/cxyhuky/cxyhuky.github.io 
repo_name: Kangying Hu's Blog

#[扩展]
extra:
    consent:
        title: Cookie consent
        description: >-
          We use cookies to recognize your repeated visits and preferences, as well
          as to measure the effectiveness of our documentation and whether users
          find what they're searching for. With your consent, you're helping us to
          make our documentation better.
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/cxyhuky

        - icon: fontawesome/solid/paper-plane
          link: mailto:cxyhuky@gmail.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - admonition    
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

#[UI]
theme:
    name: 'material'                            #主题名
    favicon: assets/logo/cxyhuky-icon.png
    language: zh
    palette:
        primary: indigo
    custom_dir: docs/templates
    icon:
        logo: material/state-machine
        repo: fontawesome/brands/github         #指定仓库图标
    features:
        - navigation.tabs                       #在header中添加导航条
        - navigation.tabs.sticky
        - navigation.top                        #回到顶部 
        - navigation.path
        - navigation.instant
        - navigation.indexes
        - navigation.prune
        - navigation.sections
        - search.suggest
        - content.code.annotate

plugins:
  - autorefs
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog:
        draft: true
  - search:
#   - minify:
#       minify_html: true
#   - bibtex:
#       bib_file: "docs/references.bib"
#       csl_file: "docs/ieee.csl"
#       cite_inline: false
        

nav:
    - Abount: index.md 
    - Computer Science:
        - cs/index.md
        - Network:
            - cs/network/application-layer.md
            - cs/network/data-link-layer.md
        - OS:
            - cs/os/learn.md
    - Reading:
        - reading/index.md
        - EffectiveJava:
            - reading/effectivejava/methods-common-to-all-objects.md
        - 图解HTTP:
            - reading/httpdiagram/created.md
        - 计算机网络（自顶向下方法）:
            - reading/computer-newworking(a-top-down-approach)/video-stream-and-cdn.md
    - Software Engineering:
        - se/index.md
        - 中间件:
          - Redis:
            - se/middleware/redis/disk-persistence.md
            - se/middleware/redis/sentinel.md
    - Blog:
        - blog/index.md